apiVersion: v1
kind: Template
metadata:
  name: jenkins-agent-maven
parameters:
- name: ODS_BITBUCKET_PROJECT
  description: Bitbucket project name.
  value: opendevstack
- name: REPO_BASE
  required: true
- name: NEXUS_URL
  required: true
- name: NEXUS_USERNAME
  required: true
- name: NEXUS_PASSWORD
  required: true
- name: ODS_IMAGE_TAG
  required: true
  value: latest
- name: ODS_GIT_REF
  required: true
- name: JENKINS_AGENT_DOCKERFILE_PATH
  value: Dockerfile.rhel7
  description: Dockerfile variant to use
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-agent-maven
    labels:
      app: jenkins-agent-maven
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-maven:${ODS_IMAGE_TAG}
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
    runPolicy: Serial
    source:
      contextDir: common/jenkins-agents/maven/docker
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/${ODS_BITBUCKET_PROJECT}/ods-quickstarters.git
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
          - name: nexusUrl
            value: ${NEXUS_URL}
          - name: nexusUsername
            value: ${NEXUS_USERNAME}
          - name: nexusPassword
            value: ${NEXUS_PASSWORD}
        dockerfilePath: ${JENKINS_AGENT_DOCKERFILE_PATH}
        from:
          kind: ImageStreamTag
          name: jenkins-agent-base:${ODS_IMAGE_TAG}
      type: Docker
    successfulBuildsHistoryLimit: 5
